get application working on local machines, requires SBT upgrade 0.13 -> 1.7 and Play 2.7 -> 2.8
* this requires bumping atom-manager-play to Play 2.8 and building a local snapshot
* bumping sbt resolves the java.lang.UnsatisfiedLinkError error and causes the following error on compilation - (Compile / twirlCompileTemplates) java.lang.NoSuchMethodError: scala.tools.nsc.Settings.bootclasspath()
* the above error is resolved by bumping Play to 2.8.8 which leads to a runtime error - com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.11.4 requires Jackson Databind version >= 2.11.0 and < 2.12.0* the jackson mapping exception is fixed by pegging the jackson versions (see github issue link in dependencies file)