upgrade sbt to latest
* this resolves the java.lang.UnsatisfiedLinkError but causes the following error on compilation: (Compile / twirlCompileTemplates) java.lang.NoSuchMethodError: scala.tools.nsc.Settings.bootclasspath()